sonar.projectKey=SEP2-assignments
sonar.projectName=shoppingcart
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000

sonar.exclusions=src/test/**
sonar.coverage.exclusions=**/shoppingcart/ShoppingCartController.java,**/shoppingcart/ShoppingCartFxApp.java,**/shoppingcart/Main.java
